#!/bin/sh
set -eu

if [ -z "${SUPABASE_URL:-}" ]; then
  echo "error: SUPABASE_URL is not set in the Xcode Cloud environment." >&2
  exit 1
fi

if [ -z "${SUPABASE_ANON_KEY:-}" ]; then
  echo "error: SUPABASE_ANON_KEY is not set in the Xcode Cloud environment." >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIGURATION_DIR="$REPO_ROOT/Cashew/Configuration"

mkdir -p "$CONFIGURATION_DIR"
cd "$CONFIGURATION_DIR"

# xcconfig files treat // as a comment marker, so keep URLs build-setting safe.
XC_SUPABASE_URL=$(printf '%s' "$SUPABASE_URL" | sed 's#//#/$()/#g')

cat > Secrets.xcconfig <<EOF
// Generated by Xcode Cloud ci_post_clone.sh. Do not commit this file.
SUPABASE_URL = $XC_SUPABASE_URL
SUPABASE_ANON_KEY = $SUPABASE_ANON_KEY
EOF
