import Foundation

extension AITripSummaryResponse {

    func toMarkdown(tripName: String) -> String {
        var out: [String] = []
        out.append("# \(tripName)")
        out.append("")

        out.append("## Overview")
        out.append(overview)
        out.append("")

        if !highlights.isEmpty {
            out.append("## Highlights")
            for h in highlights { out.append("- \(h)") }
            out.append("")
        }

        if !dailyRecap.isEmpty {
            out.append("## Day by Day")
            for recap in dailyRecap {
                let label = DateFormatting.isoDate.date(from: recap.date)
                    .map { DateFormatting.shortDayMonth.string(from: $0) } ?? recap.date
                out.append("**\(label)** — \(recap.summary)")
                out.append("")
            }
        }

        out.append("## Budget")
        if let b = budgetRecap.totalBudget {
            out.append("- Budget: \(budgetRecap.currency) \(Int(b))")
        }
        if let s = budgetRecap.totalSpent {
            out.append("- Spent: \(budgetRecap.currency) \(Int(s))")
        }
        if !budgetRecap.verdict.isEmpty {
            out.append("")
            out.append(budgetRecap.verdict)
        }
        out.append("")

        if !funFacts.isEmpty {
            out.append("## Fun Facts")
            for f in funFacts { out.append("- \(f)") }
            out.append("")
        }

        out.append("---")
        out.append("_Generated by Cashew AI Journal_")

        return out.joined(separator: "\n")
    }

    func overviewText() -> String { overview }

    func highlightsText() -> String {
        highlights.map { "• \($0)" }.joined(separator: "\n")
    }

    func dailyRecapText() -> String {
        dailyRecap.map { recap in
            let label = DateFormatting.isoDate.date(from: recap.date)
                .map { DateFormatting.shortDayMonth.string(from: $0) } ?? recap.date
            return "\(label) — \(recap.summary)"
        }.joined(separator: "\n\n")
    }

    func budgetText() -> String {
        var lines: [String] = []
        if let b = budgetRecap.totalBudget {
            lines.append("Budget: \(budgetRecap.currency) \(Int(b))")
        }
        if let s = budgetRecap.totalSpent {
            lines.append("Spent: \(budgetRecap.currency) \(Int(s))")
        }
        if !budgetRecap.verdict.isEmpty {
            lines.append(budgetRecap.verdict)
        }
        return lines.joined(separator: "\n")
    }

    func funFactsText() -> String {
        funFacts.map { "• \($0)" }.joined(separator: "\n")
    }
}
